
rgbnir_dir: data/ # rgbnir_dir/RGB/rgb_images and rgbnir_dir/NIR/nir_images
cloud_dir: cloud/ # cloud_dir/cloud_images
out_dir: results

cuda: False
gpu_ids: []

batchsize: 1
test_batchsize: 1
epoch: 200
n_data: 433
imlist: train_files.pkl
size: 256
threads: 4

lr: 0.0004
beta1: 0.5
lamb: 100
minimax: 1

gen_model: unet
gen_init: results/000038/models/gen_model_epoch_50.pth
dis_init: results/000038/models/dis_model_epoch_50.pth
in_ch: 4
out_ch: 4

manualSeed: 0
snapshot_interval: 50
